config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "application#index"

  resources :reports
  resources :groups

  get '/non_authorized', to: 'application#non_authorized'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :reports

  def total_expenses
    total = 0
    reports.each { |r| total += r.amount }
    total
  end

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :groups
  accepts_nested_attributes_for :groups

  validates :name, presence: true
  validates :amount, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reports, dependent: :destroy, foreign_key: 'author_id'
  has_many :groups, dependent: :destroy

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def non_authorized; end

  def index; end

  def after_sign_in_path_for(_resource)
    groups_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.groups
    @total = helpers.total_expenses_all
  end

  def new
    @group = Group.new
    respond_to do |format|
      format.html { render :new }
    end
  end

  def create
    user = current_user
    group = user.groups.new(group_params)

    if group.save
      flash[:notice] = 'Category added successfully'
      redirect_to groups_path
    else
      flash[:error] = group.errors.messages
      render :new
    end
  end

  def show
    @group = Group.find(params[:id])
    @reports = @group.reports.order(created_at: :desc)
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!

  def new
    @group = Group.find(params[:group_id])
    @report = Report.new
  end

  def create
    report = current_user.reports.create(report_params)
    group = Group.find(params[:group_id])
    if params[:groups].nil?
      flash[:alert] = 'Please select categories before submitting a new report'
      return redirect_to group_path(group)
    end
    params[:groups].each do |g|
      report.groups << Group.find(g)
    end
    if report.save
      flash[:notice] = 'Category added successfully'
      redirect_to group_path(group)
    else
      flash[:error] = report.errors.messages
      redirect_to new_report_path(group_id: group)
    end
  end

  private

  def report_params
    params.require(:report).permit(:name, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index; end

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_helper.rb
module GroupHelper
  def total_expenses_all
    total = 0
    Report.all.each { |r| total += r.amount }
    total
  end

  def user_authorized?(user, id)
    user.id == id
  end

  def redirect_if_authorized(user, id)
    controller.redirect_to non_authorized_path unless user_authorized?(user, id)
  end
end

app/helpers/report_helper.rb
module ReportHelper
end

app/views/application/_flash_notification.html.erb
<div class="center">
  <div>
 <% flash.each do |type, msg| %>
      <% if type == 'notice' %>
        <div class="flash-notice">
          <%= msg %>
        </div>
      <% end %>
        <% if type == 'success' %>
        <div class="flash-notice">
          <%= msg %>
        </div>
      <% end %>
      <% if type == 'error' %>
        <div class="flash-error">
          <%= msg %>
        </div>
      <% end %>
      <% if type == 'alert' %>
        <div class="flash-error">
          <%= msg %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/application/_navbar.html.erb
<header class='relative'>
  <div class="navbar-cont"></div>
  <nav class="navbar">
    <%= link_to groups_path, class: "back" do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
      </svg>
    <% end %>
    <h2 class="header"><%= page %></h2>
    <%= link_to destroy_user_session_path, method: :delete, class: "nav-logout" do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
      </svg>
    <% end %>
  </nav>
</header>

app/views/application/index.html.erb
<div class="home-page">
  <div class="title-cont">
    <h1 class="home-title">Budget Me</h1>
  </div>
  <div class="home-buttons">
    <%= button_to 'LOG IN', new_user_session_path, method: :get, class: 'log-in-btn' %>
    <%= button_to 'SIGN UP', new_user_registration_path, method: :get, class: 'sign-up-btn' %>
  </div>
</div>

app/views/application/non_authorized.html.erb
<div>
  <p>You are not authorized to view this page</p>
  <%= link_to 'Go back', groups_path %>
</div>

app/views/groups/_group_card.html.erb
<%= link_to group_path(group) do %>
  <div class="cat">
    <img src='<%= group.icon %>' width='60' />
    <div class="cat-info">
      <h3><%= group.name %></h3>
      <h3  class="cat-expense"> $<%=group.total_expenses %></h3>
    </div>
  </div>
<% end %>

app/views/groups/_report_card.html.erb
  <div class="trans">
    <h3><%= report.name %></h3>
    <span>$ <%= report.amount %></span>
  </div>

app/views/groups/index.html.erb
<div class="cat-cont">
  <%= render 'navbar', page: "CATEGORIES"%>  

  <div class="totals">
    <h2 class="text-center">Total: </h2>
    <h2>$<%= @total %></h2>
  </div>

  <div class="cat-holder">
    <% @groups.each do |group| %>
      <%= render 'group_card', group: group%>
    <% end %>
  </div>
  <div class="cat-button">
    <%= button_to 'NEW CATEGORY', new_group_path,  method: :get, class: 'new-cat-btn' %>
  </div>
</div>

app/views/groups/new.html.erb
<header class='relative'>
  <div class="navbar-cont"></div>
  <nav class="navbar">
    <%= link_to :back, class: "back" do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
      </svg>
    <% end %>
    <h2 class="header">ADD CATEGORY</h2>
  <input type="submit" value="Save" form="add-group-form" class='log-in'>
  </nav>
</header>

<div class="form">
<%= form_with model: @group, url: groups_path, method: :post, id: 'add-group-form', local: true, scope: :group do |f| %>
  <div>
  <%= f.text_field :name, size: "50x12",
placeholder: "Name", class: "name"
  %>
</div>

<div>
  <%= f.text_field :icon, size: "50x12",
placeholder: "Icon", value: "https://i.ibb.co/ysfZcX5/budget.png", class: "icon1"
  %>
</div>
<% end %>
</div>

app/views/groups/show.html.erb
<% redirect_if_authorized(current_user, @group.user.id) %>
<div class="trans-cont">
  <%= render 'navbar', page: "TRANSACTIONS" %> 

<div class="totals">
  <h2 class="text-center"><%= @group.name %> Total: </h2>
  <h2> <%= @group.total_expenses %> </h2>
</div>

<div class="trans-holder">
  <% @reports.each do |report| %>
    <%= render 'report_card', report: report%>
  <% end %>
</div>
<div class="cat-button">
<%= link_to 'New Transaction', new_report_path(group_id: @group),  method: :get, class: 'btn2' %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "flash_notification" %>
    <%= yield %>
  </body>
</html>

app/views/reports/index.html.erb
Transactions

app/views/reports/new.html.erb
<header class='relative'>
  <div class="navbar-cont"></div>
  <nav class="navbar">
    <%= link_to :back, class: "back" do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="icon" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
      </svg>
    <% end %>
    <h2 class="header">ADD TRANSACTION</h2>
  <input type="submit" value="Save" form="add-report-form" class='log-in'>
  </nav>
</header>

<%= form_with model: @report, url: reports_path, method: :post, id: 'add-report-form', local: true, scope: :report do |f| %>
   <div>
    <%= f.text_field :name, placeholder: "Name", class: "name1" %> 
  </div>

  <% current_user.groups.each do |group| %>
    <%= f.label group.name %>: 
    <%= check_box_tag "groups[]", group.id %>
  <% end %>

  <div>
    <%= f.text_field :amount, placeholder: "Amount", class: "name1" %>
  </div>

  <%= hidden_field_tag :group_id, @group.id %>
<% end %>